### ISSUE TITLE
Use unzip files rather than `.tar.xz`

### ISSUE THREAD

**Issue by HsunGong** [shsjxzh/ACM-DB#2]
We can just clone or fork the submodules, this will simplify the process.

**Comment by shsjxzh** [comment]
Thank you for your suggestions! However, for the next few labs, there will be several supplementary files provided, and providing zip files will be more organized than providing several files separately. If you are considering about the zip file type, we can provide ".zip" files. As far as I am concerned, just clicking the link and downloading the zip file is not very complicate. Thanks a lot!
