### ISSUE TITLE
Error: method HeapFile.iterator(TransactionId tid) not yet implemented!

### ISSUE THREAD

**Issue by 517030910405** [shsjxzh/ACM-DB#4]
Excuse me. 
I met the following situation. 
Is this correct? 

```
$ java -jar dist/simpledb.jar convert input/1.txt 3

$ java -jar dist/simpledb.jar print input/1.dat 3
Error: method HeapFile.iterator(TransactionId tid) not yet implemented!
```

And the **input/1.txt** is

> 1,2,3
> 2,3,4

Thank you.

**Comment by shsjxzh** [comment]
Thank you for your bug report! I rerun the code and find the same error. It seems that this part should work after you have finished lab 1 and recompile the java code (use "ant dist" command). I will move this part to lab1's introduction. Thanks a lot!
